### ISSUE TITLE
Add icon and logo to the HomeAssistant GitHub brands repository

### ISSUE THREAD

**Issue by mathieu-mp** [mathieu-mp/homeassistant-intex-spa#11]
- [x] Add icon and logo to the HomeAssistant [GitHub brands repository](https://github.com/home-assistant/brands): home-assistant/brands#3550
- [x] Remove brands ignore in hacs/action #29 
- [x] Set the hacs/default#1449 as ready
